Name:           ros-melodic-rgbd-launch
Version:        2.2.2
Release:        0%{?dist}
Summary:        ROS rgbd_launch package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/rgbd_launch
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-depth-image-proc
Requires:       ros-melodic-image-proc
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-tf2-ros
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-depth-image-proc
BuildRequires:  ros-melodic-image-proc
BuildRequires:  ros-melodic-nodelet
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-tf2-ros

%description
Launch files to open an RGBD device and load all nodelets to convert raw
depth/RGB/IR streams to depth images, disparity images, and (registered) point
clouds.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat May 19 2018 Piyush Khandelwal <piyushk@gmail.com> - 2.2.2-0
- Autogenerated by Bloom

